# Generated by Django 3.2.16 on 2022-11-22 15:49

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_objektu', models.CharField(max_length=200)),
                ('pocet_objektu', models.IntegerField()),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('borderColor', colorfield.fields.ColorField(default='#FF00FF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_grafu', models.CharField(max_length=20)),
                ('obrazek', models.ImageField(upload_to='')),
            ],
        ),
    ]
