# Generated by Django 3.2.16 on 2023-01-17 03:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=299)),
                ('pocet', models.IntegerField()),
                ('color', colorfield.fields.ColorField(default='#0010EE', image_field=None, max_length=18, samples=None)),
                ('borderColor', colorfield.fields.ColorField(default=colorfield.fields.ColorField(default='#0010EE', image_field=None, max_length=18, samples=None), image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.AlterField(
            model_name='typ',
            name='obrazek',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
