# Generated by Django 3.2.16 on 2023-01-22 16:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0002_auto_20230117_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='borderColor',
            field=colorfield.fields.ColorField(default='#0010EE', image_field=None, max_length=18, samples=None),
        ),
    ]
