# Generated by Django 3.2.16 on 2023-01-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf', '0003_alter_bar_bordercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='label',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
